// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzimzzydbqqwfznkmxsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16aW16enlkYnFxd2Z6bmtteHNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4ODIxOTEsImV4cCI6MjA3NDQ1ODE5MX0.dxQuRCKLm5-MLqsDPtz3SOQbiCyqDnCkN6qS6BSSv_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});